In [30]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os

# List all image files under the input directory and store them in a list
image_paths = []
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        if filename.lower().endswith(('.png', '.jpg', '.jpeg')):
            full_path = os.path.join(dirname, filename)
            image_paths.append(full_path)
            print(full_path)

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/car-notcars/notcars/notcar10.jpg
/kaggle/input/car-notcars/notcars/notcar7.jpg
/kaggle/input/car-notcars/notcars/notcar2.jpg
/kaggle/input/car-notcars/notcars/notcar4.jpg
/kaggle/input/car-notcars/notcars/notcar9.jpg
/kaggle/input/car-notcars/notcars/notcar8.jpg
/kaggle/input/car-notcars/notcars/notcar1.jpg
/kaggle/input/car-notcars/notcars/notcar5.jpg
/kaggle/input/car-notcars/notcars/notcar3.jpg
/kaggle/input/car-notcars/notcars/notcar6.jpg
/kaggle/input/car-notcars/cars/car12.jpg
/kaggle/input/car-notcars/cars/car1.jpg
/kaggle/input/car-notcars/cars/car9.jpg
/kaggle/input/car-notcars/cars/car4.jpg
/kaggle/input/car-notcars/cars/car10.jpg
/kaggle/input/car-notcars/cars/car5.jpg
/kaggle/input/car-notcars/cars/car11.jpg
/kaggle/input/car-notcars/cars/car13.jpg
/kaggle/input/car-notcars/cars/car2.jpg
/kaggle/input/car-notcars/cars/car3.jpg
/kaggle/input/testcarsnoncars/nontestcar/testnotcar5.jpg
/kaggle/input/testcarsnoncars/nontestcar/testnotcar3.jpg
/kaggle/input/testcar

In [31]:
import os
from skimage.io import imread
from skimage.transform import resize

# Let's define the file paths for car and not-car images according to the uploaded image
car_image_paths = [
    '/kaggle/input/car-notcars/cars/car1.jpg',
    '/kaggle/input/car-notcars/cars/car2.jpg',
    '/kaggle/input/car-notcars/cars/car3.jpg',
    '/kaggle/input/car-notcars/cars/car4.jpg',
    '/kaggle/input/car-notcars/cars/car5.jpg',
    '/kaggle/input/car-notcars/cars/car9.jpg',
    '/kaggle/input/car-notcars/cars/car10.jpg',
    '/kaggle/input/car-notcars/cars/car11.jpg',
    '/kaggle/input/car-notcars/cars/car12.jpg',
    '/kaggle/input/car-notcars/cars/car13.jpg'
]

not_car_image_paths = [
    '/kaggle/input/car-notcars/notcars/notcar1.jpg',
    '/kaggle/input/car-notcars/notcars/notcar2.jpg',
    '/kaggle/input/car-notcars/notcars/notcar3.jpg',
    '/kaggle/input/car-notcars/notcars/notcar4.jpg',
    '/kaggle/input/car-notcars/notcars/notcar5.jpg',
    '/kaggle/input/car-notcars/notcars/notcar6.jpg',
    '/kaggle/input/car-notcars/notcars/notcar7.jpg',
    '/kaggle/input/car-notcars/notcars/notcar8.jpg',
    '/kaggle/input/car-notcars/notcars/notcar9.jpg',
    '/kaggle/input/car-notcars/notcars/notcar10.jpg'
]

# Define the function to load and preprocess images
def load_and_preprocess_images(image_paths, target_size=(64, 64)):
    images = []
    for path in image_paths:
        # Read the image from the file path
        img = imread(path)
        
        # Resize the image to the target size
        img = resize(img, target_size, anti_aliasing=True)
        
        # If the image has an alpha channel, remove it
        if img.shape[2] == 4:
            img = img[..., :3]
        
        # Normalize pixel values to be between 0 and 1
        img = img.astype(np.float32) / 255.0
        
        # Flatten the image
        img_flatten = img.flatten()
        
        # Append the flattened image to the list
        images.append(img_flatten)
    
    # Stack images into a matrix
    image_matrix = np.vstack(images)
    return image_matrix

# Use the function to load car and not-car images
car_images = load_and_preprocess_images(car_image_paths)
not_car_images = load_and_preprocess_images(not_car_image_paths)

# Verify the shapes of the loaded image matrices
car_images.shape, not_car_images.shape


((10, 12288), (10, 12288))

In [32]:
image_data = load_and_preprocess_images(image_paths)


In [33]:
image_data

array([[1.0853694e-03, 1.2717748e-03, 1.3021096e-03, ..., 7.2799233e-04,
        1.0899197e-03, 2.2446839e-04],
       [1.8354665e-03, 1.7195963e-03, 1.6873118e-03, ..., 2.5620095e-03,
        2.4025026e-03, 2.3840719e-03],
       [8.9299493e-04, 1.2944702e-03, 1.3112804e-03, ..., 1.9529340e-05,
        5.0435943e-04, 6.1294239e-04],
       ...,
       [3.6139947e-03, 2.5067283e-03, 3.6447521e-03, ..., 3.6139947e-03,
        2.5067283e-03, 3.6447521e-03],
       [2.3755138e-03, 1.8193581e-03, 1.3201239e-03, ..., 1.9556191e-03,
        1.9556191e-03, 1.9248665e-03],
       [3.9215689e-03, 3.9215689e-03, 3.9215689e-03, ..., 3.9215689e-03,
        3.9215689e-03, 3.9215689e-03]], dtype=float32)

In [34]:
import torch

# We already have the preprocessed images in car_images and not_car_images.
# Convert them to PyTorch tensors
car_images_tensor = torch.tensor(car_images, dtype=torch.float32)
not_car_images_tensor = torch.tensor(not_car_images, dtype=torch.float32)

In [35]:
#Performing PCA 
def pca_step_by_step(images_tensor):
    # Standardize the images
    mean = images_tensor.mean(dim=0)
    std = images_tensor.std(dim=0) + 1e-5
    standardized_images = (images_tensor - mean) / std
    
    # Compute the covariance matrix
    covariance_matrix = torch.mm(standardized_images.t(), standardized_images) / (standardized_images.size(0) - 1)
    
    # Compute the eigenvalues and eigenvectors
    eigenvalues, eigenvectors = torch.linalg.eigh(covariance_matrix)
    
    # Sort the eigenvalues in descending order, and sort the eigenvectors to match
    sorted_indices = torch.argsort(eigenvalues, descending=True)
    sorted_eigenvalues = eigenvalues[sorted_indices]
    sorted_eigenvectors = eigenvectors[:, sorted_indices]
    
    # Select the number of components that explain 95% of the variance
    total_variance = sorted_eigenvalues.sum()
    variance_ratios = sorted_eigenvalues.cumsum(0) / total_variance
    n_components = (variance_ratios < 0.95).sum().item() + 1
    
    # Select the principal components (eigenvectors) - PCA subspace
    principal_components = sorted_eigenvectors[:, :n_components]
    
    return principal_components, mean, std, n_components

In [36]:
# Apply the step-by-step PCA to car images
principal_components_car, mean_car, std_car, n_components_car = pca_step_by_step(car_images_tensor)

# Apply the step-by-step PCA to not-car images
principal_components_not_car, mean_not_car, std_not_car, n_components_not_car = pca_step_by_step(not_car_images_tensor)

# Print the number of components and shapes of the principal components matrices
print("Car PCA components: ", n_components_car, principal_components_car.shape)
print("Not-Car PCA components: ", n_components_not_car, principal_components_not_car.shape)

Car PCA components:  8 torch.Size([12288, 8])
Not-Car PCA components:  8 torch.Size([12288, 8])


In [37]:
#PCA subspace coefficients -> projecting the images on the PCA subspace (dimensionality reduction)
projected_images_car_on_car=torch.mm((car_images_tensor-mean_car)/std_car,principal_components_car)
projected_images_car_on_not_car=torch.mm((car_images_tensor-mean_car)/std_car,principal_components_not_car)

projected_images_not_car_on_not_car=torch.mm((not_car_images_tensor-mean_not_car)/std_not_car,principal_components_not_car)
projected_images_not_car_on_car=torch.mm((not_car_images_tensor-mean_not_car)/std_not_car,principal_components_car)

print(projected_images_car_on_car.shape,projected_images_car_on_not_car.shape)
print(projected_images_car_on_car,projected_images_car_on_not_car)

print(projected_images_not_car_on_not_car.shape,projected_images_not_car_on_car.shape)
print(projected_images_not_car_on_not_car,projected_images_not_car_on_car)

torch.Size([10, 8]) torch.Size([10, 8])
tensor([[-92.3996,  21.8485,  -5.5246, -51.1915, -32.9772,  41.4920,   8.9848,
          12.6923],
        [ 58.7024, -83.3238,  18.8182, -52.6354,   4.9698, -11.9012,  10.3221,
          -5.5889],
        [-45.6675, -52.0576,  -9.2052,  41.3129, -17.1868,  -1.5775, -43.6493,
          27.4001],
        [ 30.7586,  50.2127,  -9.1391, -35.3531,  10.0584, -35.7483, -47.0419,
          -3.1496],
        [-33.4219,  -7.2585, -20.8230,  24.6934,  -8.6326, -38.6567,  40.7657,
           5.6886],
        [ 89.0806,   1.3363, -59.7714,  21.2838, -22.5094,  35.4665,  -1.1914,
         -27.6370],
        [-20.9126,  29.5792, -23.3323,   1.5863,  -1.8441, -35.1611,  19.8261,
          -2.3110],
        [-36.5417,  -1.2339, -14.4264,   7.5492,  79.6215,  27.9449,   3.9368,
           1.1004],
        [ 98.2989,  35.2882,  53.1458,  17.9211,  -2.7107,  15.4820,  14.2983,
          34.8876],
        [-47.8972,   5.6089,  70.2580,  24.8332,  -8.7888,   2.6594, 

In [38]:
test_car_image_paths=[
    '/kaggle/input/testcarsnoncars/testcar/test5.jpg',
'/kaggle/input/testcarsnoncars/testcar/testcar4.jpg',
'/kaggle/input/testcarsnoncars/testcar/testcar1.png',
'/kaggle/input/testcarsnoncars/testcar/testcar3.jpg',
'/kaggle/input/testcarsnoncars/testcar/testcar2.jpg'   
]
test_not_car_image_paths=[
    '/kaggle/input/testcarsnoncars/nontestcar/testnotcar5.jpg',
'/kaggle/input/testcarsnoncars/nontestcar/testnotcar3.jpg',
'/kaggle/input/testcarsnoncars/nontestcar/testnotcar4.jpg',
'/kaggle/input/testcarsnoncars/nontestcar/testnotcar1.jpg',
'/kaggle/input/testcarsnoncars/nontestcar/testnotcar2.jpg'
]

# Use the function to load car and not-car images
test_car_images = load_and_preprocess_images(test_car_image_paths)
test_not_car_images = load_and_preprocess_images(test_not_car_image_paths)

# Verify the shapes of the loaded image matrices
test_car_images.shape, test_not_car_images.shape


((5, 12288), (5, 12288))

In [39]:
# Convert the new test data to PyTorch tensors
test_car_images_tensor = torch.tensor(test_car_images, dtype=torch.float32)
test_not_car_images_tensor = torch.tensor(test_not_car_images, dtype=torch.float32)

# Standardize the new data using the mean and standard deviation from the training data
test_car_std = (test_car_images_tensor - mean_car) / std_car
test_not_car_std = (test_not_car_images_tensor - mean_not_car) / std_not_car

# Project the new standardized data onto the PCA subspace to get PCA subspace coefficients
test_car_pca_car = torch.mm(test_car_std, principal_components_car)
test_car_pca_not_car = torch.mm(test_car_std, principal_components_not_car)
test_not_car_pca_not_car = torch.mm(test_not_car_std, principal_components_not_car)
test_not_car_pca_car = torch.mm(test_not_car_std, principal_components_car)

print(test_car_pca_car.shape,test_not_car_pca_not_car.shape)

torch.Size([5, 8]) torch.Size([5, 8])


In [40]:
# Reconstruct the test car images from the PCA coefficients
test_car_reconstructed_car = torch.mm(test_car_pca_car, principal_components_car.t()) * std_car + mean_car
test_car_reconstructed_not_car=torch.mm(test_car_pca_car,principal_components_not_car.t())*std_not_car+mean_not_car

# Reconstruct the test not-car images from the PCA coefficients
test_not_car_reconstructed_not_car = torch.mm(test_not_car_pca_not_car, principal_components_not_car.t()) * std_not_car + mean_not_car
test_not_car_reconstructed_car = torch.mm(test_not_car_pca_not_car, principal_components_car.t()) * std_car + mean_car
# Now, test_car_reconstructed and test_not_car_reconstructed are the reconstructed images
# The shapes of the reconstructed images will match the original dimensionality of the images
test_car_reconstructed_car.shape, test_not_car_reconstructed_not_car.shape

(torch.Size([5, 12288]), torch.Size([5, 12288]))

In [43]:
#original test labels
original_test_labels=["car","car","car","car","car","not car","not car","not car","not car","not car"]

In [41]:
#Mean squared error is the reconstruction error here
def reconstruction_error(original,reconstructed):
    return ((original-reconstructed)**2).mean(dim=1)

mse_test_car_car=reconstruction_error(test_car_std,test_car_reconstructed_car)
mse_test_car_not_car=reconstruction_error(test_car_std,test_car_reconstructed_not_car)

mse_test_not_car_not_car=reconstruction_error(test_not_car_std,test_not_car_reconstructed_not_car)
mse_test_not_car_car=reconstruction_error(test_not_car_std,test_not_car_reconstructed_car)

#if error from car basis is less then classify as car else classify as not car
classification_car=mse_test_car_car<mse_test_car_not_car
classification_not_car=mse_test_not_car_not_car<mse_test_not_car_car

classified_labels_car=["car" if pred else "not car" for pred in classification_car]
classified_labels_not_car=["not car" if pred else "car" for pred in classification_not_car]

classification_results_combined=classified_labels_car+classified_labels_not_car
print("Combined classification results: ",classification_results_combined)

Combined classification results:  ['car', 'car', 'not car', 'car', 'car', 'not car', 'not car', 'car', 'not car', 'car']


In [45]:
original_labels_tensor = torch.tensor([1 if label == "car" else 0 for label in original_test_labels], dtype=torch.uint8)
predicted_labels_tensor = torch.tensor([1 if label == "car" else 0 for label in classification_results_combined], dtype=torch.uint8)
print(original_labels_tensor)
print(predicted_labels_tensor)

tensor([1, 1, 1, 1, 1, 0, 0, 0, 0, 0], dtype=torch.uint8)
tensor([1, 1, 0, 1, 1, 0, 0, 1, 0, 1], dtype=torch.uint8)


In [46]:
#Classification accuracy calculation

correct_predictions = torch.sum(predicted_labels_tensor == original_labels_tensor).item()
total_predictions = len(original_test_labels)
accuracy = correct_predictions / total_predictions
print(f"Classification accuracy: {accuracy:.2f}")

Classification accuracy: 0.70
